name: gh-pages

on:
  push:
    branches:
      - master

jobs:
  compile-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: cache yarn
        id: cache-yarn
        uses: actions/cache@v1
        with:
          path: node_modules
          key: v2-yarn-${{ hashFiles('**/yarn.lock')}}
          restore-keys: v2-yarn

      - name: cache classpath
        id: cache-classpath
        uses: actions/cache@v2
        with:
          path: |
            .cpcache
            ~/.m2/repository
          key: v1-deps-${{ hashFiles('**/deps.edn')}}
          restore-keys: v1-deps

      - name: cache shadow-cljs
        uses: actions/cache@v1
        with:
          path: .shadow-cljs
          key: v1-shadow-cljs-${{github.sha}}
          restore-keys: v1-shadow-cljs

      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.7'

      - name: Install clojure
        uses: DeLaGuardo/setup-clojure@e73bf2b6435244b2c9c5c226ae5022d91d0ce702
        with:
          tools-deps: '1.10.1.483'

      - name: Yarn
        if: steps.cache-yarn.outputs.cache-hit != 'true'
        run: yarn

      - name: Shadow-cljs
        run: yarn shadow-cljs release app

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.

      - name: print logs on failure
        if: ${{ failure() }}
        run: files=(/tmp/clojure-*) && cat $files


